core/urls.py
from django.urls import path
from core.services import (
    product,
    user,
    cart,
    order,
    product_category,
    product_inventory,
)

from core.views import ProfileView, RegistrationView


app_name = "core"

urlpatterns = [
    path("", product.ProductService.get_all_products, name="home"),
    path("sign-up/", RegistrationView.as_view(), name="sign-up"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("get-user/<int:id>", user.UserService.get_user),
    path("update-user/<int:id>", user.UserService.update_user),
    path("delete-user/<int:id>", user.UserService.delete_user),
    path("get-all-users", user.UserService.get_all_user),
    path("create-new-product", product.ProductService.create_product),
    path("get-product/<int:id>", product.ProductService.get_product),
    path("update-product/<int:id>", product.ProductService.update_product),
    path("delete-product/<int:id>", product.ProductService.delete_product),
    path("get-all-products", product.ProductService.get_all_products),
    path(
        "create-product-category",
        product_category.ProductCategoryService.create_product_category,
    ),
    path(
        "get-product-category/<int:id>",
        product_category.ProductCategoryService.get_product_category,
    ),
    path(
        "update-product-category/<int:id>",
        product_category.ProductCategoryService.update_product_category,
    ),
    path(
        "delete-product-category/<int:id>",
        product_category.ProductCategoryService.delete_product_category,
    ),
    path(
        "get-all-product-categories",
        product_category.ProductCategoryService.get_all_product_categories,
    ),
    path(
        "add-product-to-category/<int:id>",
        product_category.ProductCategoryService.add_product_to_category,
    ),
    path(
        "remove-product-from-category",
        product_category.ProductCategoryService.remove_product_from_category,
    ),
    path(
        "create-product-category-inventory",
        product_inventory.ProductInventoryService.create_product_category_inventory,
    ),
    path(
        "get-product-category-inventory/<int:id>",
        product_inventory.ProductInventoryService.get_product_category_inventory_by_id,
    ),
    path(
        "update-product-category-inventory/<int:id>",
        product_inventory.ProductInventoryService.update_product_category_inventory,
    ),
    path(
        "delete-product-category-inventory/<int:id>",
        product_inventory.ProductInventoryService.delete_product_category_inventory,
    ),
    path(
        "get-all-product-category-inventory",
        product_inventory.ProductInventoryService.get_all_product_category_inventory,
    ),
    path(
        "get-product-category-inventory-by-product",
        product_inventory.ProductInventoryService.get_product_category_inventory_by_product,
    ),
    path("create-order", order.OrderService.create_order),
    path("get-order/<int:id>", order.OrderService.get_order),
    path("update-order/<int:id>", order.OrderService.update_order),
    path("delete-order/<int:id>", order.OrderService.delete_order),
    path("create-cart", cart.CartService.create_cart),
    path("get-cart/<int:id>", cart.CartService.get_cart),
    path("update-cart/<int:id>", cart.CartService.update_cart),
    path("delete-cart/<int:id>", cart.CartService.delete_cart),
    path("clear-cart", cart.CartService.clear_cart),
    ##########################   Functional requirement APIS   ##########################
    path(
        "get-all-products-cart",
        cart.CartService.get_all_products_in_cart,
        name="get-all-products-cart",
    ),
    path(
        "add-product-to-cart",
        cart.CartService.add_product_to_cart,
        name="add-product-to-cart",
    ),
    path(
        "remove-product-from-cart",
        cart.CartService.remove_product_from_cart,
        name="remove_product_from_cart",
    ),
    path(
        "update-product-count-in-cart",
        cart.CartService.update_product_count_in_cart,
        name="update_product_count_in_cart",
    ),
    path(
        "checkout-with-order",
        cart.CartService.checkout_and_place_order,
        name="checkout_and_place_order",
    ),
    path("get-all-orders", order.OrderService.get_all_orders, name="get_all_orders"),
    path(
        "get-all-orders-by-user",
        order.OrderService.get_all_orders_by_user,
        name="get_all_orders_by_user",
    ),
]

timmarket/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("", include("core.urls", namespace="core")),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

templates/base.html
<!--templates/base.html-->
<!doctype html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


    <title>Tim-market</title>
    <style>
        body {
            padding-top: 5rem;
        }
    </style>
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a href="{% url 'core:home' %}" class="navbar-brand">Tim-market</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% if user.is_authenticated %}
        <div id="navbarCollapse" class="collapse navbar-collapse">

            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">{{user.name}}</a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a href="{% url "core:profile" %}" class="dropdown-item">Profile</a>
                        {% comment %} <a href="{% url "password_change" %}" class="dropdown-item">Change Password</a> {% endcomment %}
                        <div class="dropdown-divider"></div>
                        <a href="{% url "logout" %}" class="dropdown-item">Logout</a>
                    </div>
                </li>
            </ul>
        </div>
        {% else %}

        <div id="navbarCollapse" class="collapse navbar-collapse">

            <ul class="nav navbar-nav ml-auto">
             <a href="{% url "login" %}" style="color:powderblue;font-size:130%;">Login</a>
             </ul>
        </div>
        {% endif %}
    </nav>

    <main role="main" class="container">
        {% block content %}

        {% endblock %}

    </main>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% block content %}
  <h3 class="mt-2">Product Listings</h3>

  <div class="row">
    {% for product in data %}
      <div class="col-sm-6 col-lg-4 text-center item mb-4 flex-wrap">
        <div class="card">
          <div class="card-body">
            {% for category in product.category_details %}
              <blockquote class="blockquote mb-0">
                <footer class="blockquote-footer">
                  <small>Category: {{ category.name }}</small>
                </footer>
              </blockquote>
            {% endfor %}
          </div>

          <h3 class="text-dark"><a href="#">{{ product.name }}</a></h3>
          {% for category in product.category_details %}
            <p class="price">€{{ category.price }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}